name: e2e

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "website/**"
      - "**/example/**"
      - "**/flutterfire_ui/**"
      - "**/cloud_firestore_odm/**"
      - "**.md"
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "website/**"
      - "**/example/**"
      - "**/flutterfire_ui/**"
      - "**/cloud_firestore_odm/**"
      - "**.md"

jobs:
  android:
    runs-on: macos-12
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Install Node.js 16
        with:
          node-version: "16"
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"
      - uses: actions/cache@v2
        name: Gradle Cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-v1-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-v1
      - name: Firebase Emulator Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators
          key: firebase-emulators-v1-${{ github.run_id }}
          restore-keys: firebase-emulators-v1
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: |
          ./.github/workflows/scripts/install-tools.sh
          flutter config --no-enable-web --no-enable-ios --no-enable-macos-desktop
          sudo npm i -g firebase-tools
      - name: Start Firebase Emulator
        run: cd ./.github/workflows/scripts && ./start-firebase-emulator.sh
      - name: "E2E Tests"
        uses: reactivecircus/android-emulator-runner@v2.21.0
        timeout-minutes: 30
        with:
          api-level: 30
          arch: x86_64
          target: google_apis
          profile: Nexus 5X
          working-directory: tests
          script: flutter test integration_test/integration_e2e_test.dart --dart-define=CI=true

  ios:
    runs-on: macos-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Install Node.js 16
        with:
          node-version: "16"
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"
      - uses: hendrikmuhs/ccache-action@v1
        name: Xcode Compile Cache
        with:
          key: ${{ runner.os }}-ios-v3
          max-size: 700M
      - uses: actions/cache@v2
        name: Pods Cache
        id: pods-cache
        with:
          path: tests/ios/Pods
          key: ${{ runner.os }}-pods-v3-${{ hashFiles('tests/ios/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-ios-pods-v2
      - name: Firebase Emulator Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators
          key: firebase-emulators-v1-${{ github.run_id }}
          restore-keys: firebase-emulators-v1
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: |
          ./.github/workflows/scripts/install-tools.sh
          sudo npm i -g firebase-tools
      - name: Start Firebase Emulator
        run: cd ./.github/workflows/scripts && ./start-firebase-emulator.sh
      - name: "E2E Tests"
        working-directory: tests
        run: |
          # Boot simulator and wait for System app to be ready.
          SIMULATOR="iPhone 11"
          xcrun simctl bootstatus "$SIMULATOR" -b
          xcrun simctl logverbose "$SIMULATOR" enable
          # Sleep to allow simulator to settle.
          sleep 15
          # Uncomment following line to have simulator logs printed out for debugging purposes.
          # xcrun simctl spawn booted log stream --predicate 'eventMessage contains "flutter"' &
          flutter test integration_test/integration_e2e_test.dart --dart-define=CI=true
          FLUTTER_DRIVE_EXIT_CODE=$?
          xcrun simctl shutdown "$SIMULATOR"
          exit $FLUTTER_DRIVE_EXIT_CODE
      - name: "Swift Format Check"
        if: ${{ success() || failure() }}
        run: |
          swiftformat .
          ./.github/workflows/scripts/validate-formatting.sh

  macos:
    runs-on: macos-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Install Node.js 16
        with:
          node-version: "16"
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"
      - name: Cache Firebase Emulator
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators
          key: firebase-emulators-v1-${{ github.run_id }}
          restore-keys: firebase-emulators-v1
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: |
          ./.github/workflows/scripts/install-tools.sh
          flutter config --enable-macos-desktop
          sudo npm i -g firebase-tools
      - name: Start Firebase Emulator
        run: cd ./.github/workflows/scripts && ./start-firebase-emulator.sh
      - name: "E2E Tests"
        working-directory: tests
        run: |
          flutter drive \
            --driver=test_driver/integration_test.dart \
            --target=integration_test/app_test.dart \
            -d macos \
            --dart-define=CI=true

  web:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Install Node.js 16
        with:
          node-version: "16"
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: |
          ./.github/workflows/scripts/install-tools.sh
          flutter config --enable-web
          sudo npm i -g firebase-tools
      - name: Cache Firebase Emulator
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators
          key: firebase-emulators-v1-${{ github.run_id }}
          restore-keys: firebase-emulators-v1
      - name: Start Firebase Emulator
        run: cd ./.github/workflows/scripts && ./start-firebase-emulator.sh
      - name: "E2E Tests"
        working-directory: tests
        run: |
          chromedriver --port=4444 &
          flutter drive \
            --driver=test_driver/integration_test.dart \
            --target=integration_test/e2e_test.dart \
            -d web-server \
            --dart-define=CI=true
